apiVersion: v1
kind: Pod
metadata:
  name: test-gpu-pod
spec:
  containers:
    - name: cuda-container
      image: nvidia/cuda:11.0-devel
      resources:
        limits:
          nvidia.com/gpu: "1" # requesting 1 GPU
  tolerations:
  - effect: NoSchedule
    operator: Exists
