---
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  labels:
    app: seldon
  name: "seldon-deployment-{{workflow.name}}"
  namespace: forwardmeasure
spec:
  annotations:
    project_name: NLP Pipeline
    deployment_version: v1
  name: "seldon-deployment-{{workflow.name}}"
  predictors:
    - componentSpecs:
        - spec:
            containers:
              - image: forwardmeasure/clean_text_transformer:0.1
                imagePullPolicy: Always
                name: cleantext
                resources:
                  requests:
                    memory: 1Mi
              - image: forwardmeasure/spacy_tokenizer:0.1
                imagePullPolicy: Always
                name: spacytokenizer
                resources:
                  requests:
                    memory: 1Mi
              - image: forwardmeasure/tfidf_vectorizer:0.1
                imagePullPolicy: Always
                name: tfidfvectorizer
                resources:
                  requests:
                    memory: 1Mi
                volumeMounts:
                  - name: mypvc
                    mountPath: /mnt
              - image: forwardmeasure/lr_text_classifier:0.1
                imagePullPolicy: Always
                name: lrclassifier
                resources:
                  requests:
                    memory: 1Mi
                volumeMounts:
                  - name: mypvc
                    mountPath: /mnt
            terminationGracePeriodSeconds: 20
            volumes:
              - name: mypvc
                persistentVolumeClaim:
                  claimName: "{{workflow.name}}-my-pvc"
      graph:
        children:
          - name: spacytokenizer
            endpoint:
              type: REST
            type: MODEL
            children:
              - name: tfidfvectorizer
                endpoint:
                  type: REST
                type: MODEL
                children:
                  - name: lrclassifier
                    endpoint:
                      type: REST
                    type: MODEL
                    children: []
        name: cleantext
        endpoint:
          type: REST
        type: MODEL
      name: single-model
      replicas: 1
      annotations:
        predictor_version: v1
